<?php

App::uses('FizzBuzz', 'Lib');

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-10-12 at 10:27:30.
 */
class FizzBuzzTest extends CakeTestCase {

	/**
	 * @var FizzBuzz
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	public function setUp() {
		parent::setUp();
		$this->object = new FizzBuzz;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	public function tearDown() {
		unset($this->object);
		parent::tearDown();
	}

	/**
	 * @covers FizzBuzz::fizzbuzz
	 */
	public function testFizzbuzz() {
		$this->assertEquals(1, FizzBuzz::fizzbuzz(1));
	}

}
